# automatically generated by g-sorcery
# please do not edit this file

EAPI=5

REALNAME="django-statici18n"
REALVERSION="1.1.3"
REPO_URI="http://pypi.python.org/packages/source/${REALNAME:0:1}/${REALNAME}/"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
PYTHON_COMPAT=( python{2_7,2_7,2_7,3_2,3_3,3_4,3_2,3_3} )

inherit gs-pypi

DESCRIPTION="A Django app that provides helper for generating Javascript catalog to static files."

HOMEPAGE="http://django-statici18n.readthedocs.org/"
LICENSE="BSD"

SLOT="0"
KEYWORDS="~amd64 ~x86"

